#
# Executes commands at login pre-zshrc.
#
#   This file is similar to zlogin, but it is sourced before zshrc. It was added for KornShell fans. See the description of zlogin below for what it may contain.
#     zprofile and zlogin are not meant to be used concurrently but can be done so.
#

#
# Browser
#

if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='edge'
fi

#
# Editors
#

export EDITOR='vim'
export VISUAL='macvim'
export PAGER='less'

#
# Language
#

if [[ -z "$LANG" ]]; then
  export LANG='en_US.UTF-8'
fi

#
# Paths
#

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

# Set the list of directories that Zsh searches for programs.
path=(
  /usr/local/opt/python/libexec/bin
  /usr/local/opt/rabbitmq/sbin
  /usr/local/{bin,sbin}
  /usr/local/opt/binutils/bin
  /usr/local/opt/util-linux/{bin,sbin}
  /usr/local/opt/curl/bin
  /usr/local/opt/ruby/bin
  /usr/local/lib/ruby/gems/2.7.0/bin
  /usr/local/lib/ruby/gems/2.6.0/bin
  /opt/X11/bin
  $HOME/.bin
  $HOME/.cargo/bin
  /usr/{bin,sbin}
  /{bin,sbin}
)

#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-F -g -i -M -R -S -w -X -z-4'

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
if (( $#commands[(i)lesspipe(|.sh)] )); then
  export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi


