#
# Defines environment variables.
#
#   define all environment variables here
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

# Source other env variables
if [[ -s "${ZDOTDIR:-$HOME}/.zsecrets" ]]; then
  source "${ZDOTDIR:-$HOME}/.zsecrets"
fi


# ENV VARIABLES
# Add folders/locations to $PATH
case `uname` in
    Darwin)
        source ~/.zdarwin
    ;;
esac

# Gpg TTY
GPG_TTY=$(tty)
export GPG_TTY

ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=245,faint"
