#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

# Source other env variables
source ~/.zsecrets

#source /usr/local/Cellar/goto/1.2.3/etc/bash_completion.d/goto.sh

# ENV VARIABLES
# Add folders/locations to $PATH
export PATH="$HOME/bin:$PATH";
export PATH="$PATH:/usr/local/sbin";
export PATH="$PATH:$HOME/.cargo/bin"
export PATH="$PATH:/Applications/Visual Studio Code.app/Contents/Resources/app/bin"
export PATH="/usr/local/opt/binutils/bin:$PATH"
export PATH="/usr/local/lib/ruby/gems/2.6.0/bin:$PATH"
export PATH="/usr/local/opt/ruby/bin:$PATH"
export PATH="/Users/jniec/.chefdk/gem/ruby/2.6.0/bin:$PATH"

# Set Github API token for Homebrew
#export HOMEBREW_GITHUB_API_TOKEN=296b9f4ae43a4e37832f48751797eb753f82a03a

# Go path settings
export GOPATH="~/.go"
export GOBIN="~/.go/bin"

# Ruby pkgconfig path
export PKG_CONFIG_PATH="/usr/local/opt/ruby/lib/pkgconfig"

# Gpg TTY
GPG_TTY=$(tty)
export GPG_TTY

ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=245,faint"
