#
# Executes commands at the start of an interactive session.
#
#   This file is sourced by interactive shells. It should define aliases, functions, shell options, and key bindings.
#
#Performance Profiling
zmodload zsh/zprof

# Hub = Github
eval "$(hub alias -s)"

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

## Source Zsh/Bash Completion
source /usr/local/etc/profile.d/z.sh
source <(kubectl completion zsh)
source ~/.fzf.zsh
source '/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/path.zsh.inc'
source '/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/completion.zsh.inc'

## Aliases
alias cat='bat --style=plain'
alias ls='exa'
alias sudo=$'nocorrect sudo\t'
alias man=$'nocorrect man\t'
alias k='kubectl'
alias i='istioctl'
alias tf='terraform'
alias ipcalc='sipcalc -a'
alias code='code .'
alias grep='rg'

## SSH function with Chromaterm
ssh() { /usr/bin/ssh $* | ct; }

complete -F __start_kubectl k

ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets pattern cursor root)

# Prints profiling
#zprof
