#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#
#zmodload zsh/zprof
# Set git = hub
eval "$(hub alias -s)"

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi



# Source
source ~/.zshenv
source ~/.zprofile
source <(kubectl completion zsh)

# The following lines were added by compinstall

zstyle ':completion:*' completer _complete _ignored
zstyle :compinstall filename "$HOME/.zshrc"

autoload -Uz compinit
compinit
# End of lines added by compinstall

source /usr/local/Cellar/goto/1.2.3/etc/bash_completion.d/goto.sh
source /usr/local/share/zsh-autosuggestions/zsh-autosuggestions.zsh
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

function gcd {
  REPO=$1
  CLONEPATH=$2

  if [ -z $CLONEPATH ]; then
      CLONEPATH=${$(basename $1)/.git/}
  fi

  git clone $REPO $CLONEPATH
  cd $CLONEPATH
}

## Aliases
alias cat='bat --style=plain'
alias ls='exa'

alias sudo=$'nocorrect sudo\t'
alias man=$'nocorrect man\t'
alias k='kubectl'
alias i='istioctl'
alias tf='terraform'
alias ipcalc='ipcalc -n'

ssh() { /usr/bin/ssh $* | ct; }

autoload -U +X bashcompinit && bashcompinit
#complete -o nospace -C /usr/local/bin/vault vault

export PATH="$HOME/.jenv/bin:$PATH"
#eval "$(jenv init -)"

#zprof
