# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

#
# Executes commands at the start of an interactive session.
#
#   This file is sourced by interactive shells. It should define aliases, functions, shell options, and key bindings.
#
#Performance Profiling
#zmodload zsh/zprof

# Backwards Kill Character Alphanumeric Only
autoload -U select-word-style
select-word-style bash

# Hub = Github
eval "$(hub alias -s)"

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

## Source Zsh/Bash Completion
source /usr/local/etc/profile.d/z.sh
source <(kubectl completion zsh)
source ~/.fzf.zsh
source '/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/path.zsh.inc'
source '/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/completion.zsh.inc'

## Aliases
alias cat='bat --style=plain'
alias ls='exa'
alias sudo=$'nocorrect sudo\t'
alias man=$'nocorrect man\t'
alias k='kubectl'
alias i='istioctl'
alias tf='terraform'
alias ipcalc='sipcalc -a'
alias code='code .'
alias grep='rg'

## SSH function with Chromaterm
ssh() { /usr/bin/ssh $* | ct; }

complete -F __start_kubectl k

ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets pattern cursor root)

# Prints profiling
#zprof

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
